export const Vietnamese = {
    languageChosen: "Vietnamese",
    language: {
        EN: "English",
        VN: "Tiếng Việt",
    },
    modal: {
        pleaseWait: "Đang Tải...",
        sending: "Đang Gửi...",
        msgSent: "Tin nhắn đã được gửi thành công",
    },
    dayInWeek: {
        sunday: "Chủ Nhật",
        monday: "Thứ Hai",
        tuesday: "Thứ Ba",
        wednesday: "Thứ Tư",
        thursday: "Thứ Năm",
        friday: "Thứ Sáu",
        saturday: "Thứ Bảy",
    },
    messageModal: {
        title: "Tin Nhắn Từ Trang ONTHECARD",
        of: "Của",
        deleteConfirm: "Bạn có xác nhận muốn xoá tin nhắn này ?",
        deleteMessage: "Xoá Tin Nhắn",
        return: "Quay Lại",
        messageDeleted: "Tin nhắn đã được xoá",
        close: "Đóng",
        sendEmail: "Gửi Email",
        call: "Gọi Điện",
        noMessage: "Bạn chưa có tin nhắn nào",
        search: "Tìm Tin Nhắn",
        update: "Cập Nhật",
        searchTitle: "Tìm Kiếm Tin Nhắn Của Bạn",
        name: "Nhập Tên, Email Hoặc Số Điện Thoại...",
        search2: "Tìm Kiếm",
        fullList: "Toàn Bộ Tin Nhắn",
    },
    backendErrors: {
        takenEmailMsg: "The email address is already in use by another account.",
        takenEmailAlert: "Email này đã được đăng ký bởi 1 thẻ khác. Vui lòng chọn email khác !",
        invalidPasswordMsg: "The password is invalid or the user does not have a password.",
        invalidPasswordAlert: "Mật khẩu không đúng, vui lòng nhập lại mật khẩu !",
        noEmailMsg: "There is no user record corresponding to this identifier. The user may have been deleted.",
        noEmailAlert: "Email không đúng hoặc chưa được đăng ký trong hệ thống. Vui lòng nhập lại email !",
        otherError: "Lỗi đăng nhập: ",
    },
    errors: {
        authenticatedNoUserName: "Lỗi Hệ Thống !",
        validation: {
            fieldRequired: "Vui lòng điền vào trường này !",
            invalidEmail: "Email Không Hợp Lệ. Vui Lòng Nhập Lại Email !",
            specialCaseDot: "Tên Truy Cập Không Thể Có Dấu '.'",
            specialCaseHash: "Tên Truy Cập Không Thể Có Dấu '#'",
            specialCaseDollar: "Tên Truy Cập Không Thể Có Dấu '$'",
            specialCaseSquarOpen: "Tên Truy Cập Không Thể Có Dấu '['",
            specialCaseSplash: "Tên Truy Cập Không Thể Có Dấu '/'",
            specialCaseSquareClose: "Tên Truy Cập Không Thể Có Dấu ']'",
            specialCaseSpace: "Vui Lòng Viết Liền Các Ký Tự",
            lengthValidate13: "Mã Số Thẻ Bắt Buộc Bao Gồm 13 Số.",
            lengthValidate8: "Mật Khẩu Bắt Buộc Ít Nhất 8 Ký Tự.",
            userNameNotAvailable: "Vui Lòng Đổi Tên Truy Cập Khác. Tên Truy Cập Đã Được Đăng Ký Trước Đây !",
            serialInvalid: "Vui Lòng Kiểm Tra Lại Mã Số Thẻ. Mã Số Thẻ Không Có Trong Hệ Thống !",
            serialTaken: "Vui Lòng Kiểm Tra Lại Mã Số Thể. Mã Số Thẻ Này Đã Được Đăng Ký Bởi Người Dùng Khác",
            invalidExtension: "Đuôi '.con' không hợp lệ. Vui Lòng Nhập Lại Email.",
            invalidFullName: "Vui lòng điền tên của bạn",
            invalidPhoneNumber: "Vui lòng điền Số Điện Thoại của bạn",
            invalidMessage: "Vui lòng điền Lời Nhắn của bạn",
            invalidEmailMessage: "Vui lòng điền Email của bạn",
        },
    },
    signUp: {
        title: "Tạo Tài Khoản",
        title2: "ONTHECARD Của Bạn",
        email: "Email",
        fullname: "Tên Của Bạn",
        fullnamehint: "Nhập tên của bạn muốn hiển thị trên website",
        usernamehint:"Ví dụ nếu bạn đặt tên truy cập là 'thanhdat' thì tên miền website của bạn sẽ là 'onthecard.me/thanhdat'",
        username: "Tên Truy Cập ",
        password: "Mật Khẩu",
        confirm: "Xác Nhận Mật Khẩu",
        serialCode: "Mã Số Thẻ",
        already: "Nếu bạn đã có tài khoản. ",
        placeHolder: {
            email: "Nhập Email",
            fullname: "Nhập Tên Của Bạn",
            username: "Nhập Tên Truy Cập",
            serialNo: "Nhập Mã Số Thẻ",
            password: "Nhập Mật Khẩu",
        },
        modal: {
            wait: "Đang Tải...",
            confirm1: "Đăng Ký Thành Công",
            confirm2: "Email xác nhận đăng ký đã được gửi đến email của bạn.",
        },
        button: {
            signup: "Tạo Tài Khoản",
            signin: "Đăng Nhập",
        },
    },
    signIn: {
        title: "Chào mừng bạn",
        title2: "đến với ONTHECARD !",
        email: "Email / Tên Truy Cập",
        password: "Mật Khẩu",
        signUpTitle: "Chưa có tài khoản? ",
        placeHolder: {
            email: "Nhập Email hoặc Tên Truy Cập",
            password: "Nhập Mật Khẩu",
        },
        button: {
            signup: "Đăng Ký Tại Đây",
            signin: "Đăng Nhập",
            forgot: "Quên Mật Khẩu?",
            loginFacebook: "Đăng Nhập Với Facebook",
            loginGoogle: "Đăng Nhập Với Google",
        },
    },
    retrieve: {
        title: "Quên Mật Khẩu",
        email: "Email",
        placeHolder: {
            email: "Nhập Email",
        },
        explain: "Nhập email của bạn, hệ thống sẽ gửi bạn email để cài đặt lại mật khẩu",
        box: "Nhập Email Ở Đây",
        button: "Cài Đặt Lại Mật Khẩu",
        signin: "Quay Lại Đăng Nhập",
        h3text: "Email đã được gửi đến",
        h3text2: "Vui lòng kiểm tra email của bạn !",
        notice: "Lưu Ý:",
        warning: "Vui lòng kiểm tra thư mới trong mục Thư Chính (Primary) và Quảng Cáo (Promotions) trong tài khoản email của bạn !",
        dismiss: "Đóng",
    },
    profile: {
        button: {
            logout: "Đăng Xuất",
            edit: "Chỉnh Sửa Trang",
            editPage: "Chỉnh Sửa Trang Cá Nhân",
            myProfile: "Tài Khoản Của Tôi",
            advanced: "Nâng Cao",
            message: "Tin Nhắn",
            lock: "Khoá Trang",
            unlock: "Mở Khoá Trang",
            unlockShort: "Mở Khoá",
            close: "Đóng",
        },
        modal: {
            title: "Bạn Có Muốn Tạm Thời Khoá Trang ?",
            subtext: "Sau khi khoá trang, mọi người sẽ không thể thấy trang ONTHECARD của bạn. Bạn có thể mở khoá trang bất cứ khi nào bạn muốn.",
            unlockTitle: "Bạn Có Muốn Mở Khoá Trang ?",
            unlockSub: "Sau khi mở khoá trang, mọi người sẽ có thể thấy trang ONTHECARD của bạn. Bạn có thể khoá trang bất cứ khi nào bạn muốn.",
            lockSuccess: "Khoá Trang Thành Công",
            unlockSuccess: "Mở Khoá Trang Thành Công",
        },
    },
    analytic: {
        visit: "Truy Cập",
        redirect: "Chạm Thẻ",
        saveContact: "Lưu Danh Bạ",
        clickCount: "Lượt Click",
        click: "Lượt",
        count: "Lượt",
        title1: "Tổng Quan Trang ONTHECARD",
        title2: "Của",
        title3: "Phân Tích Lượt Truy Cập",
        update: "Cập Nhật Dữ Liệu",
    },
    editPage: {
        uploadImageTexts: {
            uploadImage: "Đăng Ảnh",
            addImage: "Thêm Ảnh",
        },
        text: {
            myPage: "Link Của Bạn: ",
            name: "Tên",
            bio: "Thông Tin Về Bạn",
            addNew: "Thêm Đường Link Và Tài Khoản",
            redirectMessage: "Vui lòng thêm đường link để bật chế độ chuyển trang !",
            thumbnail: "Thêm ảnh icon (dưới 10mb)",
            imgModalAlert: "Vui lòng nhập đường link và miêu tả đường link !",
            embedModalAlert: "Đường Link không hợp lệ. Vui lòng nhập lại đường link.",
            errorsHappened: "Errors happened. Please try again",
            embedYoutube: "Nhúng Video",
            bankingInfo: "Số Tài Khoản Ngân Hàng",
        },
        button: {
            manageLink: "Quản Lý Link",
            editProfile: "Thông Tin",
            copy: "Copy Link",
            copyNo: "Copy Số",
            copied: "Đã Copy",
            updateButton: "Lưu Thông Tin",
            addLink: "Thêm Link",
            preview: "Xem Trang",
            delete: "Xoá",
            editLink: "Chỉnh Sửa",
            updateInfo: "Cập Nhật Thông Tin",
            analytic: "Tổng Quan",
            comingSoon: "Coming Soon",
            message: "Tin Nhắn",
        },
        modal: {
            loading: "Đang Tải....",
            embed: "Nhúng",
            demo: "Demo Đường Link",
            confirm: "Thay Đổi Thành Công !",
            gotIt: "Đóng",
            alert: "Vui lòng nhập những thông tin cần thiết để thêm tài khoản !",
            alert2: "Vui lòng nhấn 'Chọn Tài Khoản' để chọn tài khoản bạn muốn thêm",
            enter: {
            link: "Nhập Đường Link...",
            email: "Email",
            phone: "Số Phone",
            bankInfo: "Số Tài Khoản",
            username: "Tên Người Dùng",
            usernameOrPhone: "Số Phone, Tên Người Dùng",
            namePlaceHolder: "Miêu Tả Đường Link...",
            musicPlaceHolder: "Tên Bài Hát / Tên Channel",
            artistPlaceHolder: "Tên Nghệ Sĩ",
            enterYoutube: "Nhập Đường Link Youtube Video...",
            enterBanking: "Nhập Số Tài Khoản Ngân Hàng....",
            },
            remind: "Lưu ý: vui lòng đóng thông báo này và nhấn Lưu Thông Tin để cập nhật dữ liệu của bạn.",
            hint: "Lưu ý",
            hintText1: "Hãy nhớ nhấn vào nút ",
            hintText2: "ở dưới sau khi bạn đăng tải hình ảnh này",
        },
        dropDown: {
            selectAccount: "Chọn Tài Khoản",
            phone: "Số Phone",
            otherLink: "Đường Link Khác",
            otherLinkAdvanced: "Đường Link Khác (Nâng Cao)",
            momo: "Ví Momo",
            editLink: "Chỉnh Sửa Đường Link",
            embedYoutube: "Nhúng Youtube Video",
            banking: "Tài Khoản Ngân Hàng",
        },
    },
    viewPage: {
        saveConact: "Lưu Liên Lạc",
        connect: "Nhắn Nhủ",
        titleQRModal: "Chia Sẻ Trang ONTHECARD",
        subQRModal: "Của",
        subtitleQR: "Chia sẻ với bạn bè, đối tác bằng cách scan mã QR dưới đây",
        messageForm: {
            leaveMessage: "Để Lại Lời Nhắn Cho",
            fullName: "Tên Của Bạn...",
            email: "Email...",
            phoneNumber: "Số Điện Thoại...",
            message: "Nội Dung Lời Nhắn...",
            sendMessage: "Gửi Lời Nhắn",
            emailMe: "Email cho tôi trang của",
            success: "Lời nhắn đã được gửi thành công.",
            error: "Có vấn đề xảy ra, vui lòng thử lại",
            errorToken: "Đã có vấn đề xảy ra. Vui lòng reload trang và thử lại. \n(token error)",
            messageFrom: "Tin Nhắn Từ",
        },
    },
    customizePage: {
        title: "Cá Nhân Hoá",
        styleOptions: "Cá Nhân Hoá Ảnh Nền",
        colorSection: "Màu Nền",
        style: "Lọc Màu Nền",
        color: "Tiêu Chuẩn",
        light: "Sáng",
        dark: "Tối",
        background: "Ảnh Nền",
        addImage: "Thêm Ảnh",
        replaceImage: "Thay Ảnh",
        deleteImage: "Xoá Ảnh",
        updateButton: "Lưu Thông Tin",
        original: "Nguyên Bản",
        black: "Đen",
        blue: "Xanh",
        iconSection: "Màu Sắc Icon",
    },
    redirect: {
        modeOn: "Chuyển Trang Bật",
        modeOff: "Chuyển Trang Tắt",
        saveContactOn: "Chạm Lưu Danh Bạ Bật",
        saveContactOff: "Chạm Lưu Danh Bạ Tắt",
    },
    footer: {
        smartCard: "Thẻ Cá Nhân Thông Minh Hàng Đầu Tại",
        vietnam: "Việt Nam",
    },
};
  
export const English = {
    languageChosen: "English",
    language: {
        EN: "English",
        VN: "Tiếng Việt",
    },
    modal: {
        pleaseWait: "Please Wait...",
        sending: "Sending Your Message...",
        msgSent: "Message successfully sent",
    },
    dayInWeek: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
    },
    messageModal: {
        title: "Message Sent Via ONTHECARD",
        of: "Of",
        deleteConfirm: "Do you want to delete this message ?",
        deleteMessage: "Delete",
        return: "Return",
        messageDeleted: "This message has been deleted",
        close: "Close",
        sendEmail: "Email",
        call: "Call",
        noMessage: "You don't have any message",
        search: "Search Message",
        update: "Update Message",
        searchTitle: "Search For Your Message",
        name: "Sender's Name, Email, Phone Number...",
        search2: "Search Message",
        fullList: "Full Messages List",
    },
    backendErrors: {
        takenEmailMsg: "The email address is already in use by another account.",
        takenEmailAlert: "The email address is already in use by another account.",
        invalidPasswordMsg: "The password is invalid or the user does not have a password.",
        invalidPasswordAlert: "The password is invalid. Please try another password !",
        noEmailMsg: "There is no user record corresponding to this identifier. The user may have been deleted.",
        noEmailAlert: "Email incorrect or wasn't registered",
        otherError: "Login Error: ",
    },
    errors: {
        authenticatedNoUserName: "System Errors !",
        validation: {
            fieldRequired: "*Field Required !",
            invalidEmail: "Invalid Email !",
            specialCaseDot: "Invalid '.' Symbol.",
            specialCaseHash: "Invalid '#' Symbol.",
            specialCaseDollar: "Invalid '$' Symbol.",
            specialCaseSquarOpen: "Invalid '[' Symbol.",
            specialCaseSplash: "Invalid '/' Symbol.",
            specialCaseSquareClose: "Invalid ']' Symbol.",
            specialCaseSpace: "No space is allowed in this textbox",
            lengthValidate13: "Serial No. must have at least 13 numbers",
            lengthValidate8: "Password requires at least 8 characters.",
            userNameNotAvailable: "Username is not available !",
            serialInvalid: "Serial Number is not existed in our system",
            serialTaken: "Serial Number was registered by other account",
            invalidExtension: "Email: invalid '.con' extension",
            invalidFullName: "Vui lòng điền tên của bạn",
            invalidPhoneNumber: "Vui lòng điền Số Điện Thoại của bạn",
            invalidMessage: "Vui lòng điền Lời Nhắn của bạn",
            invalidEmailMessage: "Vui lòng điền Email của bạn",
        },
    },
    signUp: {
        title: "Create Your",
        title2: "ONTHECARD Account",
        email: "Email",
        fullname: "Full Name",
        fullnamehint: "Visible On Profile",
        usernamehint: "onthecard.me/username",
        username: "Username",
        password: "Password",
        confirm: "Confirm Password",
        serialCode: "Serial Code",
        already: "Already had an account? ",
        placeHolder: {
            email: "Enter Email",
            fullname: "Enter Your Full Name",
            username: "Enter User Name",
            serialNo: "Enter Serial Number",
            password: "Enter Password",
        },
        modal: {
            wait: "Load....",
            confirm1: "Sign Up Sucessfully",
            confirm2: "Please Check Your Email For Verification !",
        },
        button: {
            signup: "Create Your Profile",
            signin: "Sign In",
        },
    },
    signIn: {
        title: "Welcome to the",
        title2: "Future with ONTHECARD!",
        email: "Email / UserName",
        password: "Password",
    
        signUpTitle: "Don't have an account yet ? ",
        placeHolder: {
            email: "Enter Email or UserName",
            password: "Enter Password",
        },
        button: {
            signup: "Sign Up Here",
            signin: "Sign In",
            forgot: "Forgot Your Account ?",
            loginFacebook: "Login With Facebook",
            loginGoogle: "Login With Google",
        },
    },
    retrieve: {
        title: "Forgot Password",
        placeHolder: {
            email: "Enter Email",
        },
        email: "Email",
        explain: "Enter your email, we'll send you an email shortly about your account information",
        box: "Enter Your Email",
        button: "Retrieve Account",
        signin: "Return to Login",
        h3text: "An email has been sent to",
        h3text2: "Please Check Your Email !",
        notice: "Notice:",
        warning: "Make sure to check Primary and Promotions sections in your gmail account !",
        dismiss: "Dismiss",
    },
    profile: {
        button: {
            logout: "Log Out",
            edit: "Edit Page",
            editPage: "Edit Page",
            myProfile: "My Account",
            advanced: "Advanced",
            message: "Message",
            lock: "Deactivate Page",
            unlock: "Activate Page",
            unlockShort: "Activate Page",
            close: "Close",
        },
        modal: {
            title: "Do You Want To Deactivate Your Page Temporary ?",
            subtext: "When you Deactivate, no one will be able to see your ONTHECARD page. You can re-activate your page at anytime.",
            unlockTitle: "Do You Want To Reactivate Your Page ?",
            unlockSub: "When you Reactivate, everyone will be able to see your ONTHECARD page. You can de-activate your page at anytime.",
            lockSuccess: "Your Page Is Deactivated",
            unlockSuccess: "Your Page Is Activated",
        },
    },
    analytic: {
        visit: "Page Visit",
        redirect: "Card Redirection",
        saveContact: "Save Contact",
        clickCount: "Click Count",
        count: "",
        click: "Clicks",
        title1: "ONTHECARD Analytic Data",
        title2: "For",
        title3: "Links Analytic",
        update: "Update Data",
    },
    editPage: {
        uploadImageTexts: {
            uploadImage: "Upload Image",
            addImage: "Add Image",
        },
        text: {
            myPage: "Your Link: ",
            name: "Name",
            bio: "Bio",
            addNew: "Add New Links And Channel",
            redirectMessage: "Please add new link to turn Redirect Mode on",
            thumbnail: "Image Thumbnail (size limit 10mb)",
            imgModalAlert: "Please enter link and link description to add new link",
            embedModalAlert: "Invalid Youtube Video URL. Please try again !",
            errorsHappened: "Something Happens. Please Try Again !",
            embedYoutube: "Embeddable Media",
            bankingInfo: "Banking Information",
        },
        button: {
            manageLink: "Manage Link",
            editProfile: "Basic Info",
            copy: "Copy Link",
            copied: "Copied",
            copyNo: "Copy Banking Info",
            updateButton: "Save Info",
            addLink: "Add Link",
            preview: "View Page",
            delete: "Delete",
            editLink: "Edit",
            updateInfo: "Update Info",
            analytic: "Analytic",
            comingSoon: "Coming Soon",
            message: "Message",
        },
    
        modal: {
            loading: "Loading...",
            demo: "Preview",
            embed: "Embed",
            confirm: "Update Sucessfully !",
            gotIt: "Got It !",
            alert: "Please enter URL / Username / Phone Number to add your account !",
            alert2: "Please Press 'Select Account' Button To Select Your Account",
            enter: {
            link: "Enter Link...",
            email: "Enter Email...",
            phone: "Enter Phone Number...",
            username: "Username...",
            bankInfo: "Banking Info",
            usernameOrPhone: "Phone Number or Username",
            namePlaceHolder: "Enter Link Name...",
            musicPlaceHolder: "Song's Name / Channel Name...",
            artistPlaceHolder: "Artist Name...",
            enterYoutube: "Enter Youtube URL...",
            enterBanking: "Enter Banking Information...",
            },
            remind: "Notice: please close this notification and hit Save Changes to update your information",
            hint: "Notice",
            hintText1: "Remember to hit ",
            hintText2: "button down below after you upload this image",
        },
        dropDown: {
            selectAccount: "Select Account",
            phone: "Phone Number",
            otherLink: "Other Link",
            otherLinkAdvanced: "Other Link (Advanced)",
            momo: "Momo Wallet",
            editLink: "Edit Link",
            embedYoutube: "Embed Youtube Video",
            banking: "Banking Information",
        },
    },
    viewPage: {
        saveConact: "Save Contact",
        connect: "Connect",
        titleQRModal: "Share ONTHECARD Page",
        subQRModal: "For",
        subtitleQR: "Share with friends by having them scan the QR code",
        messageForm: {
            leaveMessage: "Để Lại Lời Nhắn Cho",
            fullName: "Tên Của Bạn...",
            email: "Email...",
            phoneNumber: "Số Điện Thoại...",
            message: "Nội Dung Lời Nhắn...",
            sendMessage: "Gửi Lời Nhắn",
            emailMe: "Email cho tôi trang của",
            success: "Lời nhắn đã được gửi thành công.",
            error: "Có vấn đề xảy ra, vui lòng thử lại",
            errorToken: "Đã có vấn đề xảy ra. Vui lòng reload trang và thử lại. \n(token error)",
            messageFrom: "Message From",
        },
    },
    customizePage: {
        title: "Customize",
        styleOptions: "Style Options",
        colorSection: "Color",
        color: "Color",
        style: "Style",
        light: "Light",
        dark: "Dark",
        background: "Background Image",
        addImage: "Add Image",
        replaceImage: "Replace Image",
        deleteImage: "Delete Image",
        updateButton: "Update Changes",
        original: "Original",
        black: "Black",
        blue: "Blue",
        iconSection: "Icon Color",
    },
    redirect: {
        modeOn: "Redirect On",
        modeOff: "Redirect Off",
        saveContactOn: "Redirect Save Contact On",
        saveContactOff: "Redirect Save Contact Off",
    },
    footer: {
        smartCard: "Leading Smart Business Card Solution in Vietnam",
    },
};